/// Generates typed column-definition part files from annotated data classes.
///
/// Quality-program-v3 item 8 (codegen path). Scans `.dart` sources for
/// classes annotated with `@OsGridColumn()` and emits a sibling
/// `<file>.g.part` containing:
///
/// * a `<className camelCase>Columns({overrides})` function returning a
///   typed `List<OsColumnDef<T>>`, with real typed value getters
///   (`(p) => p.name`) — no stringly-typed field lookups;
/// * a `<ClassName>Cols` constants class of phantom-typed `ColumnRef`s
///   (item 38).
///
/// Usage:
/// ```
/// dart run tool/os_column_gen.dart [directory] [--check]
/// ```
///
/// The generator uses regex/brace scanning only — no mirrors, no
/// build_runner, no new package dependencies (zero-dep rule). It understands
/// plain field declarations (`final Type name;` / `Type name;`), optional
/// `@OsColumn(...)` annotations, and skips methods, constructors and
/// comments. Deliberately conservative: anything it cannot parse is skipped,
/// never guessed.
library;

import 'dart:io';

const String _generatedMarker =
    '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
    '// Generated by tool/os_column_gen.dart (quality-program-v3 #8).\n';

const String _ignoreForFile = '// ignore_for_file: unused_import\n';

/// A parsed `@OsColumn(...)` annotation: raw argument key → literal text.
class ParsedFieldAnnotation {
  /// Builds an annotation record from raw literal arguments.
  const ParsedFieldAnnotation(this.args);

  /// Raw literal arguments, e.g. `{'headerName': "'Name'", 'width': '150'}`.
  final Map<String, String> args;

  /// Whether any metadata was supplied.
  bool get isEmpty => args.isEmpty;
}

/// A parsed class field eligible for column derivation.
class ParsedField {
  /// Builds a parsed field record.
  const ParsedField({
    required this.name,
    required this.typeName,
    required this.isFinal,
    this.annotation,
  });

  /// Declared Dart name of the field.
  final String name;

  /// Declared type as written (`String`, `int`, `List<int>`, …).
  final String typeName;

  /// Whether the declaration is `final` (immutable → no value setter).
  final bool isFinal;

  /// Attached `@OsColumn(...)`, when present.
  final ParsedFieldAnnotation? annotation;
}

/// A parsed `@OsGridColumn`-annotated class.
class ParsedClass {
  /// Builds a parsed class record.
  const ParsedClass({
    required this.name,
    required this.fields,
    this.configArgs = const {},
  });

  /// Class name.
  final String name;

  /// Ordered eligible fields (class-level `exclude` applies at emit time via
  /// the runtime factory).
  final List<ParsedField> fields;

  /// Raw class-level `@OsGridColumn(...)` literal arguments.
  final Map<String, String> configArgs;
}

/// Maps a declared type name to the schema kind used by the runtime factory.
String kindForType(String typeName) {
  const map = <String, String>{
    'String': 'text',
    'int': 'integer',
    'double': 'number',
    'num': 'number',
    'bool': 'boolean',
    'DateTime': 'date',
  };
  return map[typeName] ?? 'custom';
}

/// Lowercases the first character (`Person` → `person`).
String lowerFirst(String s) =>
    s.isEmpty ? s : '${s[0].toLowerCase()}${s.substring(1)}';

/// File name component of a POSIX- or Windows-style path.
String baseName(String path) {
  final normalized = path.replaceAll('\\', '/');
  final idx = normalized.lastIndexOf('/');
  return idx == -1 ? normalized : normalized.substring(idx + 1);
}

/// Strips line and block comments while preserving string literals well
/// enough for source scanning (adjacent-literal concatenation edge cases
/// aside).
String stripComments(String source) {
  return source.replaceAllMapped(
    RegExp(
      r"'(?:\\.|[^'\\])*'"
      r'|"(?:\\.|[^"\\])*"'
      r'|//[^\n]*'
      r'|/\*.*?\*/',
      dotAll: true,
    ),
    (m) => m.group(0)!.startsWith('/') ? '' : m.group(0)!,
  );
}

/// Index of the `)` closing the group opened at [openParen], honouring
/// nesting and string literals. -1 when unbalanced.
int matchingParen(String s, int openParen) {
  var depth = 0;
  var inString = false;
  for (var i = openParen; i < s.length; i++) {
    final c = s[i];
    if (inString) {
      if (c == r'\') i++;
      if (c == "'" || c == '"') inString = false;
      continue;
    }
    if (c == "'" || c == '"') {
      inString = true;
    } else if (c == '(') {
      depth++;
    } else if (c == ')') {
      depth--;
      if (depth == 0) return i;
    }
  }
  return -1;
}

/// Splits a top-level comma list into trimmed segments.
List<String> splitTopLevel(String s) {
  final parts = <String>[];
  var depth = 0;
  var inString = false;
  final buf = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    final c = s[i];
    if (inString) {
      buf.write(c);
      if (c == r'\') {
        i++;
        if (i < s.length) buf.write(s[i]);
        continue;
      }
      if (c == "'" || c == '"') inString = false;
      continue;
    }
    if (c == "'" || c == '"') {
      inString = true;
      buf.write(c);
    } else if (c == '(' || c == '[' || c == '{') {
      depth++;
      buf.write(c);
    } else if (c == ')' || c == ']' || c == '}') {
      depth--;
      buf.write(c);
    } else if (c == ',' && depth == 0) {
      parts.add(buf.toString());
      buf.clear();
    } else {
      buf.write(c);
    }
  }
  final rest = buf.toString();
  if (rest.trim().isNotEmpty) parts.add(rest);
  return parts.map((p) => p.trim()).where((p) => p.isNotEmpty).toList();
}

/// Parses `key: value` pairs from an annotation argument body.
Map<String, String> parseAnnotationArgs(String body) {
  final result = <String, String>{};
  for (final part in splitTopLevel(body)) {
    final idx = part.indexOf(':');
    if (idx <= 0) continue;
    final key = part.substring(0, idx).trim();
    if (!RegExp(r'^[A-Za-z_][A-Za-z0-9_]*$').hasMatch(key)) continue;
    result[key] = part.substring(idx + 1).trim();
  }
  return result;
}

/// Extracts the balanced `{…}` body starting at [openBrace].
String extractBraceBody(String s, int openBrace) {
  var depth = 0;
  var inString = false;
  for (var i = openBrace; i < s.length; i++) {
    final c = s[i];
    if (inString) {
      if (c == r'\') i++;
      if (c == '"' || c == "'") inString = false;
      continue;
    }
    if (c == "'" || c == '"') {
      inString = true;
    } else if (c == '{') {
      depth++;
    } else if (c == '}') {
      depth--;
      if (depth == 0) return s.substring(openBrace + 1, i);
    }
  }
  return '';
}

final RegExp _annotationClassPattern = RegExp(
  r'@OsGridColumn\b\s*(?:\(([^()]*(?:\([^()]*\)[^()]*)*)\))?\s*'
  r'(?:abstract\s+)?(?:base\s+)?(?:interface\s+)?(?:final\s+)?(?:sealed\s+)?'
  r'(?:mixin\s+)?class\s+(\w+)',
);

/// Parses all `@OsGridColumn`-annotated classes out of [source], in
/// declaration order.
List<ParsedClass> parseAnnotatedClasses(String source) {
  final clean = stripComments(source);
  final classes = <ParsedClass>[];

  for (final match in _annotationClassPattern.allMatches(clean)) {
    final className = match.group(2)!;
    final braceIdx = clean.indexOf('{', match.end);
    if (braceIdx == -1 || clean.substring(match.end, braceIdx).contains(';')) {
      continue; // forward declaration or malformed — skip
    }
    final body = extractBraceBody(clean, braceIdx);

    final fields = <ParsedField>[];
    for (final decl in _topLevelStatements(body)) {
      final field = tryParseField(decl);
      if (field != null) fields.add(field);
    }

    final rawArgs = match.group(1);
    classes.add(
      ParsedClass(
        name: className,
        fields: fields,
        configArgs: rawArgs == null || rawArgs.trim().isEmpty
            ? const {}
            : parseAnnotationArgs(rawArgs),
      ),
    );
  }
  return classes;
}

/// Yields member-level chunks of a class [body].
///
/// A chunk ends at either a top-level `;` or — for members with block
/// bodies (methods, constructors, getters) — just before the body's `{`,
/// skipping the block entirely. Initialiser braces (`= {…}`, `: {…}`,
/// `=> {…}`) stay part of the chunk.
Iterable<String> _topLevelStatements(String body) sync* {
  var depth = 0;
  var start = 0;
  var inString = false;
  for (var i = 0; i < body.length; i++) {
    final c = body[i];
    if (inString) {
      if (c == r'\') i++;
      if (c == "'" || c == '"') inString = false;
      continue;
    }
    if (c == "'" || c == '"') {
      inString = true;
      continue;
    }
    final isBlockOpener =
        c == '{' && depth == 0 && !_isInitializerBrace(body, i);
    if (isBlockOpener) {
      // Member body: emit the declaration head, then skip the block.
      var end = i;
      while (end > start && _isSpace(body[end - 1])) {
        end--;
      }
      if (end > start) yield body.substring(start, end);
      i = _matchingBrace(body, i);
      start = i + 1;
      continue;
    }
    if (c == '(' || c == '[' || c == '{') {
      depth++;
    } else if (c == ')' || c == ']' || c == '}') {
      depth--;
    } else if (c == ';' && depth == 0) {
      yield body.substring(start, i);
      start = i + 1;
    }
  }
}

bool _isSpace(String c) => c == ' ' || c == '\t' || c == '\n' || c == '\r';

/// Whether the `{` at [idx] opens an initialiser expression rather than a
/// member body (`= {`, `: {`, `=> {`, `return {` style contexts).
bool _isInitializerBrace(String s, int idx) {
  var j = idx - 1;
  while (j >= 0 && _isSpace(s[j])) {
    j--;
  }
  if (j < 0) return false;
  final prev = s[j];
  if (prev == '=' || prev == ':' || prev == '(' || prev == ',') return true;
  if (prev == '>' && j >= 1 && s[j - 1] == '=') return true; // =>
  return false;
}

/// Index of the `}` matching the `{` at [openIdx] (string-aware), or
/// [openIdx] itself when unbalanced.
int _matchingBrace(String s, int openIdx) {
  var depth = 0;
  var inString = false;
  for (var i = openIdx; i < s.length; i++) {
    final c = s[i];
    if (inString) {
      if (c == r'\') i++;
      if (c == "'" || c == '"') inString = false;
      continue;
    }
    if (c == "'" || c == '"') {
      inString = true;
    } else if (c == '{') {
      depth++;
    } else if (c == '}') {
      depth--;
      if (depth == 0) return i;
    }
  }
  return openIdx;
}

/// Words that can begin a declaration but are never a type name.
const Set<String> _keywords = {
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'base',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'covariant',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'get',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'late',
  'library',
  'mixin',
  'new',
  'null',
  'on',
  'operator',
  'part',
  'required',
  'rethrow',
  'return',
  'sealed',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'while',
  'with',
  'yield',
};

bool _looksLikeType(String token) =>
    !_keywords.contains(token) &&
    RegExp(r'^[A-Za-z_][A-Za-z0-9_]*(?:<[^();={}]*>)?\??$').hasMatch(token);

/// Attempts to parse one statement as an eligible field declaration.
/// Returns null for methods, constructors, getters and anything unshaped.
ParsedField? tryParseField(String statement) {
  var work = statement.trim();
  while (work.endsWith(';')) {
    work = work.substring(0, work.length - 1).trimRight();
  }

  // Peel a leading @OsColumn(...) annotation off the front.
  ParsedFieldAnnotation? annotation;
  final annMatch = RegExp(r'^@OsColumn\b\s*\(').firstMatch(work);
  if (annMatch != null) {
    final open = annMatch.end - 1;
    final close = matchingParen(work, open);
    if (close == -1) return null;
    annotation = ParsedFieldAnnotation(
      parseAnnotationArgs(work.substring(open + 1, close)),
    );
    work = work.substring(close + 1).trim();
  }

  if (work.startsWith('@')) return null; // unsupported annotation carrier
  if (RegExp(r'[()]').hasMatch(work)) return null; // fn-ish: skip
  if (RegExp(r'\b(?:get|set)\b').hasMatch(work)) return null; // accessors

  // Drop any initializer (everything from the first top-level `=`).
  final eqIdx = work.indexOf('=');
  if (eqIdx != -1) work = work.substring(0, eqIdx).trim();

  final tokens = _splitTokens(work);
  if (tokens.isEmpty) return null;

  var idx = 0;
  var isFinal = false;
  var sawTypedDecl = false;
  while (idx < tokens.length) {
    final t = tokens[idx];
    if (t == 'static') {
      idx++;
    } else if (t == 'late') {
      idx++;
    } else if (t == 'final') {
      isFinal = true;
      sawTypedDecl = true;
      idx++;
    } else if (t == 'const') {
      return null; // const fields are compile-time data, not columns
    } else if (t == 'var') {
      sawTypedDecl = false;
      idx++;
      break;
    } else {
      break;
    }
  }
  final rest = tokens.sublist(idx);
  String name;
  if (!sawTypedDecl && rest.length == 1) {
    name = rest.single; // `var name`
  } else if (rest.length >= 2 && _looksLikeType(rest.first)) {
    name = rest.last; // `Type name`
  } else {
    return null;
  }

  if (!_isValidFieldName(name)) return null;
  final typeName = rest.length >= 2 ? rest.first : 'dynamic';
  return ParsedField(
    name: name,
    typeName: typeName.replaceAll(RegExp(r'\s+'), ''),
    isFinal: isFinal,
    annotation: annotation,
  );
}

/// Splits on whitespace outside of angle brackets / strings.
List<String> _splitTokens(String s) {
  final tokens = <String>[];
  var depth = 0;
  final buf = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    final c = s[i];
    if (c == '<') depth++;
    if (c == '>') depth--;
    if (c == ' ' || c == '\t') {
      if (depth <= 0 && buf.isNotEmpty) {
        tokens.add(buf.toString());
        buf.clear();
        continue;
      }
      if (depth > 0) buf.write(c);
      continue;
    }
    buf.write(c);
  }
  if (buf.isNotEmpty) tokens.add(buf.toString());
  return tokens;
}

bool _isValidFieldName(String name) =>
    RegExp(r'^[a-z][A-Za-z0-9_]*$').hasMatch(name);

/// Annotation keys understood by both runtime and emitter.
const Set<String> supportedMetaKeys = {
  'headerName',
  'colId',
  'width',
  'minWidth',
  'maxWidth',
  'flex',
  'sortable',
  'resizable',
  'hide',
  'pinned',
  'editable',
  'singleClickEdit',
  'autoHeight',
  'wrapText',
  'suppressMenu',
  'lockVisible',
  'lockPinned',
  'lockPosition',
  'rowGroup',
  'pivot',
  'aggFunc',
  'tooltipField',
  'headerTooltip',
  'filter',
};

const Set<String> _supportedConfigKeys = {
  'colIdPrefix',
  'defaultWidth',
  'defaultSortable',
  'defaultResizable',
};

/// Renders one `OsColumnField<T>` list element for [field].
String emitFieldLiteral(String className, ParsedField field) {
  final ctor = 'OsColumnField<$className>.${kindForType(field.typeName)}';
  final args = <String>["'${field.name}'", '(p) => p.${field.name}'];
  if (!field.isFinal) {
    args.add('setValue: (p, v) => p.${field.name} = v as ${field.typeName}');
  }
  final meta = field.annotation;
  if (meta != null && !meta.isEmpty) {
    final rendered = _renderLiterals(meta.args, supportedMetaKeys);
    if (rendered.isNotEmpty) args.add('meta: OsColumn($rendered)');
  }

  final oneLine = '$ctor(${args.join(', ')})';
  if (oneLine.length <= 78 || args.length <= 2) return oneLine;
  final indented = args.map((a) => '        $a').join(',\n');
  return '$ctor(\n$indented,\n      )';
}

String _renderLiterals(Map<String, String> args, Set<String> keys) {
  final parts = <String>[];
  for (final entry in args.entries) {
    if (!keys.contains(entry.key)) continue;
    parts.add('${entry.key}: ${entry.value}');
  }
  return parts.join(', ');
}

String _emitConfigLiteral(Map<String, String> configArgs) {
  final rendered = _renderLiterals(configArgs, _supportedConfigKeys);
  if (rendered.isEmpty) return 'OsGridColumn()';
  return 'OsGridColumn($rendered)';
}

/// Emits the complete `.g.part` content for [classes].
///
/// [partOfName] is the owning library file name (e.g. `'person.dart'`).
String generatePartFile({
  required String partOfName,
  required List<ParsedClass> classes,
}) {
  final out = StringBuffer()
    ..write(_generatedMarker)
    ..writeln('// To regenerate, run:')
    ..writeln('//   dart run tool/os_column_gen.dart')
    ..writeln('// Owning library must import:')
    ..writeln("//   package:os_grid_flutter/os_grid_flutter.dart")
    ..writeln()
    ..write(_ignoreForFile)
    ..writeln("part of '$partOfName';")
    ..writeln();

  for (final cls in classes) {
    final fnName = '${lowerFirst(cls.name)}Columns';
    final colsName = '${cls.name}Cols';

    out
      ..writeln('/// Typed column definitions derived from [${cls.name}].')
      ..writeln('///')
      ..writeln(
        '/// Pass per-field [overrides] (keyed by field name) to supply',
      )
      ..writeln('/// behaviour annotations cannot express (custom renderers,')
      ..writeln('/// comparators, formatters). An override replaces the base')
      ..writeln(
        '/// definition but is back-filled with its accessor and identity.',
      )
      ..writeln('List<OsColumnDef<${cls.name}>> $fnName({')
      ..writeln('  Map<String, OsColumnDef<${cls.name}>> overrides = const {},')
      ..writeln('}) {')
      ..writeln('  return OsColumnDefs.fromSchema<${cls.name}>(')
      ..writeln('    OsColumnSchema<${cls.name}>(')
      ..writeln('      type: ${cls.name},')
      ..writeln('      config: ${_emitConfigLiteral(cls.configArgs)},')
      ..writeln('      fields: [');

    for (final field in cls.fields) {
      out.writeln('        ${emitFieldLiteral(cls.name, field)},');
    }

    out
      ..writeln('      ],')
      ..writeln('    ),')
      ..writeln('    overrides: overrides,')
      ..writeln('  );')
      ..writeln('}')
      ..writeln()
      ..writeln(
        '/// Phantom-typed column references for [${cls.name}] '
        '(quality-program-v3 #38).',
      )
      ..writeln('abstract final class $colsName {');

    for (final field in cls.fields) {
      out
        ..writeln('  /// Reference to the `${field.name}` column.')
        ..writeln(
          "  static const ${field.name} = "
          "ColumnRef<${cls.name}>.unchecked('${field.name}');",
        );
    }

    out
      ..writeln('}')
      ..writeln();
  }

  return out.toString();
}

/// Generates `.g.part` files for every annotated source under [directory].
///
/// Returns written paths. When [check] is true nothing is written and a
/// [GenerationCheckFailure] is thrown if any output would change.
List<String> generateInDirectory(Directory directory, {bool check = false}) {
  final touched = <String>[];
  final entities = directory.listSync(recursive: true)
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final entity in entities) {
    if (entity is! File) continue;
    final name = baseName(entity.path);
    if (!name.endsWith('.dart')) continue;
    if (name.endsWith('.g.dart') || name.endsWith('.g.part')) continue;
    // Test fixtures often embed annotation samples in string literals.
    if (name.startsWith('_') || name.endsWith('_test.dart')) continue;

    final source = entity.readAsStringSync();
    if (!source.contains('@OsGridColumn')) continue;

    final classes = parseAnnotatedClasses(source);
    if (classes.isEmpty) continue;

    final output = generatePartFile(partOfName: name, classes: classes);
    final stem = name.substring(0, name.length - '.dart'.length);
    final outFile = File(
      '${entity.parent.path}${Platform.pathSeparator}$stem.g.part',
    );

    final exists = outFile.existsSync();
    if (!exists || outFile.readAsStringSync() != output) {
      if (check) throw GenerationCheckFailure(outFile.path);
      outFile.writeAsStringSync(output);
      touched.add(outFile.path);
    }
  }
  return touched;
}

/// Thrown by [generateInDirectory] in check mode when output drifts.
class GenerationCheckFailure implements Exception {
  /// Creates a failure for [path].
  GenerationCheckFailure(this.path);

  /// The stale file path.
  final String path;

  @override
  String toString() =>
      'Generated file out of date: $path\nRe-run '
      '`dart run tool/os_column_gen.dart`.';
}

void main(List<String> args) {
  var dir = '.';
  var check = false;
  for (final arg in args) {
    if (arg == '--check') {
      check = true;
    } else if (!arg.startsWith('-')) {
      dir = arg;
    } else {
      stderr.writeln('Unknown option: $arg');
      exitCode = 64;
      return;
    }
  }

  final directory = Directory(dir);
  if (!directory.existsSync()) {
    stderr.writeln('Directory not found: $dir');
    exitCode = 66;
    return;
  }

  try {
    final touched = generateInDirectory(directory, check: check);
    if (check) {
      stdout.writeln('os_column_gen --check OK');
    } else if (touched.isEmpty) {
      stdout.writeln('os_column_gen: nothing to generate.');
    } else {
      stdout.writeln('os_column_gen wrote ${touched.length} file(s):');
      for (final path in touched) {
        stdout.writeln('  $path');
      }
    }
  } on GenerationCheckFailure catch (e) {
    stderr.writeln(e.toString());
    exitCode = 65;
  }
}
